name: CI/CD Laravel 12 Pipeline

# Workflow được kích hoạt khi có push hoặc pull_request trên nhánh main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    name: Build & Test Laravel App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, bcmath, xml, curl, json, gd, pdo, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      # Nếu muốn chạy migration trên cơ sở dữ liệu test (ví dụ dùng SQLite in-memory)
      - name: Run migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"

      - name: Run tests
        run: php artisan test

  deploy:
    name: Deploy Laravel App
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Deploy chỉ chạy trên nhánh main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      # Nếu ứng dụng của bạn có sử dụng Laravel Mix hoặc vite để build assets:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install npm dependencies
        run: npm install
      - name: Build assets
        run: npm run production

      # Deploy đến server qua SSH (đảm bảo đã thiết lập các secrets SERVER_HOST, SERVER_USER, SERVER_SSH_KEY)
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/my-laravel-app
            git pull origin main
            composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader
            php artisan migrate --force
            npm install
            npm run production
            php artisan cache:clear
