name: CI/CD Laravel 12 Pipeline

# Workflow được kích hoạt khi có push hoặc pull_request trên nhánh main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    name: Build & Test Laravel App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4.2"
          extensions: mbstring, bcmath, xml, curl, json, gd, pdo, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Copy .env file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      # Nếu muốn chạy migration trên cơ sở dữ liệu test (ví dụ dùng SQLite in-memory)
      - name: Run migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"

      - name: Run tests
        run: php artisan test
