name: CI/CD Laravel 12 Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    name: Build & Test Laravel App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4.2" # Chọn phiên bản PHP phù hợp với Laravel 12
          extensions: mbstring, bcmath, xml, curl, json, gd, pdo, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Setup Environment File
        run: |
          if [ ! -f .env ]; then
            cp .env.example .env
          fi

      - name: Generate Application Key
        run: php artisan key:generate --force

      - name: Run Migrations
        run: php artisan migrate --force
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"

      - name: Run Tests
        run: php artisan test

      # Nếu cần, bạn có thể thêm bước kiểm tra bổ sung (ví dụ: lint, code style)
      - name: Code Style Check
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        run: |
          # Ví dụ: nếu bạn dùng PHP_CodeSniffer
          vendor/bin/phpcs --standard=PSR12 app/ routes/ tests/
